# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title High-Dimensional Robust Mean Estimation via Gradient Descent using Rcpp
#' @description High-Dimensional Robust Mean Estimation via Gradient Descent using Rcpp
#' @param matrix Design matrix over \eqn{R^{p \times n}}, \code{n} is the number of random vectors, \code{p} is the dimension of random vectors
#' @param epsilon Estimated proportion of outliers in a dataset
#' @param max_iter The maximum number of iterations of the algorithm
#' @param tol The convergence coefficient of the algorithm
#' @return A weight vector for a weighted mean estimate
#' @examples
#' \dontrun{
#' random_matrix_normal <- matrix(rnorm(20000, mean = 0, sd = 1), nrow = 200, ncol = 100)
#' w <- projected_gradient_descent(random_matrix_normal, epsilon)
#' mu_w <- random_matrix_normal %*% w
#' print("The weighted mean estimate:")
#' }
#' @export
projected_gradient_descent <- function(matrix, epsilon, max_iter = 1000L, tol = 1e-5) {
    .Call('_SA24204187_projected_gradient_descent', PACKAGE = 'SA24204187', matrix, epsilon, max_iter, tol)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsSamplingC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsSamplingC <- function(N, thin) {
    .Call('_SA24204187_gibbsSamplingC', PACKAGE = 'SA24204187', N, thin)
}

